// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apninbhrxrprrbcqgdeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbmluYmhyeHJwcnJiY3FnZGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjQxMTksImV4cCI6MjA2Nzc0MDExOX0.jLtXQobNMoHpVE8NA7YI5xirX9QZFANn5IEXhHEQpAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});